base_url = "https://gorest.co.in"
url_access_type = "/public-api"
base_url_spotify = "https://api.spotify.com/v1"
bearer_token = "8TTk4F_1fdVIqz7j5nK8QyQ8a-UHyA0wzDEJ"
spotify_token = "BQCL-KsKozisOP8UHo4oT8xGZQqoHqaeaiLIVrrI2ECDQL31np3UeYvl3ibIOHhDz8c7QYX3thNs3vw_IQ2ZGZhw2iztrDKZtJspdOKJALCLiK-gDeOCBFqDtVEaKyo1fpQtsnN4NjOMO74sW2BTXqSqu8anFWpS8LtGBVpj2lMms3cNuahsUJV6-hPY3hq1gz_m-UJENM0mM69IBnajEo1wL5awA8ZoEqmIvrK-GCMfNJcMD3foI6ZUqlbgvK8ANd24AEzBhklwNaoPaQqhrEk"